/* ==========================================================================
   Search — full-text search across every document and the glossary.

   Opened by the top bar's Search button or ⌘K / Ctrl+K (see bh.js). The index,
   theme/search-index.js, is generated by `npm run index` and loaded on first open.
   Every word typed must match (in the title, section heading or text); matches in titles
   and headings rank higher. ↑/↓ move, Enter opens, Esc closes. Results link straight to
   the section (#id). Not available in bundled single files (no site to search).
   ========================================================================== */
(function () {
  "use strict";
  const bh = window.bh;
  const { el } = bh;
  const root = bh.siteRoot;
  const MAX_RESULTS = 25, SNIPPET = 150;
  let dialog, input, list, status, data = null, results = [], active = 0, uid = 0;

  const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

  function load() {
    if (window.BH_SEARCH) return Promise.resolve(window.BH_SEARCH);
    return bh.loadScript(new URL("theme/search-index.js", root).href).then(() => window.BH_SEARCH || []);
  }

  function score(terms, page, sec) {
    const title = page.title.toLowerCase(), head = sec.heading.toLowerCase(), text = sec.text.toLowerCase();
    let total = 0;
    for (const t of terms) {
      const inTitle = title.includes(t), inHead = head.includes(t), inText = text.includes(t);
      if (!inTitle && !inHead && !inText) return 0;
      total += (inTitle ? 8 : 0) + (inHead ? 5 : 0) + (inText ? 1 : 0);
      const start = new RegExp(`(^|[^a-z0-9])${escapeRe(t)}`);
      if (start.test(title) || start.test(head)) total += 2; // word starts beat substrings
    }
    return total;
  }

  function run(query) {
    const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
    if (!terms.length) {
      // No query: every document, for quick navigation.
      return data.filter((p) => p.kind !== "glossary").map((page) => ({ page, sec: page.sections[0] || { id: "", heading: "", text: "" }, terms }));
    }
    const out = [];
    for (const page of data) for (const sec of page.sections) {
      const s = score(terms, page, sec);
      if (s) out.push({ page, sec, terms, s: s + (sec.id ? 0 : 0.5) });
    }
    return out.sort((a, b) => b.s - a.s).slice(0, MAX_RESULTS);
  }

  /** Text with every term wrapped in <mark>, built from text nodes (no innerHTML). */
  function highlighted(text, terms) {
    const frag = document.createDocumentFragment();
    if (!terms.length) { frag.append(text); return frag; }
    const re = new RegExp(`(${terms.map(escapeRe).join("|")})`, "gi");
    text.split(re).forEach((part, i) => frag.append(i % 2 ? el("mark", { text: part }) : part));
    return frag;
  }

  function snippet(text, terms) {
    if (!text) return "";
    const lower = text.toLowerCase();
    const at = Math.min(...terms.map((t) => lower.indexOf(t)).filter((i) => i >= 0), Infinity);
    if (!isFinite(at) || at < SNIPPET / 3) return text.slice(0, SNIPPET) + (text.length > SNIPPET ? "…" : "");
    const start = Math.max(0, at - SNIPPET / 3);
    return "…" + text.slice(start, start + SNIPPET) + (start + SNIPPET < text.length ? "…" : "");
  }

  function href(r) { return new URL(r.page.href + (r.sec.id ? "#" + r.sec.id : ""), root).href; }

  function render() {
    results = run(input.value);
    active = Math.min(active, Math.max(0, results.length - 1));
    list.replaceChildren(...results.map((r, i) => {
      const a = el("a", { href: href(r), tabindex: "-1" }, [
        el("span", { class: "bh-search-title" }, [
          el("span", { class: "badge plain bh-search-kind", text: r.page.kind }),
          highlighted(r.page.title, r.terms),
          r.sec.heading ? el("span", { class: "bh-search-section" }, [" › ", highlighted(r.sec.heading, r.terms)]) : null,
        ]),
        r.terms.length || r.page.kind === "glossary" ? el("span", { class: "bh-search-snippet" }, [highlighted(snippet(r.sec.text, r.terms), r.terms)]) : null,
      ]);
      a.addEventListener("click", () => close());
      const li = el("li", { role: "option", id: `bh-sr-${uid}-${i}`, "aria-selected": String(i === active) }, [a]);
      li.addEventListener("pointermove", () => { if (active !== i) { active = i; mark(); } });
      return li;
    }));
    status.textContent = input.value.trim()
      ? `${results.length || "No"} result${results.length === 1 ? "" : "s"}`
      : `${results.length} documents · type to search them and the glossary`;
    mark();
  }

  function mark() {
    [...list.children].forEach((li, i) => li.setAttribute("aria-selected", String(i === active)));
    const cur = list.children[active];
    if (cur) { input.setAttribute("aria-activedescendant", cur.id); cur.scrollIntoView({ block: "nearest" }); }
    else input.removeAttribute("aria-activedescendant");
  }

  function build() {
    uid += 1;
    input = el("input", {
      type: "search", class: "bh-search-input", placeholder: "Search documents and the glossary…",
      role: "combobox", "aria-expanded": "true", "aria-controls": `bh-sr-list-${uid}`, "aria-autocomplete": "list", "aria-label": "Search",
    });
    list = el("ul", { class: "bh-search-results", role: "listbox", id: `bh-sr-list-${uid}`, "aria-label": "Results" });
    status = el("p", { class: "bh-search-status", "aria-live": "polite" });
    dialog = el("dialog", { class: "bh-search", "aria-label": "Search" }, [
      el("div", { class: "bh-search-head" }, [input]),
      list,
      el("div", { class: "bh-search-foot" }, [status, el("span", { class: "muted", text: "↑ ↓ move · Enter open · Esc close" })]),
    ]);
    input.addEventListener("input", () => { active = 0; render(); });
    input.addEventListener("keydown", (e) => {
      if (e.key === "ArrowDown") { e.preventDefault(); active = Math.min(results.length - 1, active + 1); mark(); }
      else if (e.key === "ArrowUp") { e.preventDefault(); active = Math.max(0, active - 1); mark(); }
      else if (e.key === "Enter" && results[active]) { e.preventDefault(); const to = href(results[active]); close(); location.href = to; }
    });
    // Click on the backdrop (outside the panel) closes.
    dialog.addEventListener("click", (e) => { if (e.target === dialog) close(); });
    document.body.append(dialog);
  }

  function open() {
    if (!root) return Promise.resolve();
    if (!dialog) build();
    if (!dialog.open) dialog.showModal();
    input.select();
    return load().then((d) => { data = d; render(); });
  }

  function close() { if (dialog && dialog.open) dialog.close(); }

  bh.search = { open, close, run: (q) => (data ? run(q) : []) };
  window.bhModules = Object.assign(window.bhModules || {}, { "search.js": true });
})();
