/* GENERATED by `npm run index` from docs/glossary.html. Edit that page, not this file. */
window.BH_GLOSSARY = [
  {
    "id": "adr",
    "term": "ADR",
    "aliases": [
      "ADRs",
      "architecture decision record",
      "architecture decision records"
    ],
    "html": "<p>An architecture decision record: a short, permanent note of one significant decision, covering its context, the options considered and the consequences. ADRs are superseded by new records rather than edited.</p>",
    "href": "docs/glossary.html#adr"
  },
  {
    "id": "backoff",
    "term": "Backoff",
    "aliases": [
      "exponential backoff"
    ],
    "html": "<p>Waiting longer after each failed attempt before retrying, usually doubling the delay each time. Without <a href=\"docs/glossary.html#jitter\">jitter</a>, clients that failed together retry together.</p>",
    "href": "docs/glossary.html#backoff"
  },
  {
    "id": "burst",
    "term": "Burst",
    "aliases": [
      "bursts"
    ],
    "html": "<p>A short spike of requests above the average rate. In a token bucket, the largest burst allowed is the bucket's capacity <em>b</em>.</p>",
    "href": "docs/glossary.html#burst"
  },
  {
    "id": "cache-miss",
    "term": "Cache miss",
    "aliases": [
      "cache misses"
    ],
    "html": "<p>A lookup that finds nothing in the cache, so the request falls through to the slower source of truth and usually back-fills the cache.</p>",
    "href": "docs/glossary.html#cache-miss"
  },
  {
    "id": "gcra",
    "term": "GCRA",
    "aliases": [
      "generic cell rate algorithm"
    ],
    "html": "<p>The generic cell rate algorithm. It is equivalent to a token bucket, but stores one timestamp per key: the theoretical arrival time of the next conforming request.</p>\n        <p><a href=\"https://en.wikipedia.org/wiki/Generic_cell_rate_algorithm\">Generic cell rate algorithm (Wikipedia)</a></p>",
    "href": "docs/glossary.html#gcra"
  },
  {
    "id": "jitter",
    "term": "Jitter",
    "aliases": [],
    "html": "<p>Randomness added to retry or polling delays, so many clients that start together don't keep acting in lock-step and overload a recovering service.</p>",
    "href": "docs/glossary.html#jitter"
  },
  {
    "id": "leaky-bucket",
    "term": "Leaky bucket",
    "aliases": [
      "leaky buckets"
    ],
    "html": "<p>A queue that drains at a fixed rate. It smooths output to a constant pace instead of allowing bursts; compare with a <a href=\"docs/glossary.html#token-bucket\">token bucket</a>.</p>",
    "href": "docs/glossary.html#leaky-bucket"
  },
  {
    "id": "monotonic-clock",
    "term": "Monotonic clock",
    "aliases": [
      "monotonic clocks"
    ],
    "html": "<p>A clock that only moves forwards. Use it to measure elapsed time, because the wall clock can jump backwards when NTP corrects it.</p>",
    "href": "docs/glossary.html#monotonic-clock"
  },
  {
    "id": "p99",
    "term": "p99",
    "aliases": [
      "99th percentile"
    ],
    "html": "<p>The 99th-percentile latency: 99% of requests complete at least this fast. Tail latency like this, rather than the average, is what users notice.</p>",
    "href": "docs/glossary.html#p99"
  },
  {
    "id": "rate-limiting",
    "term": "Rate limiting",
    "aliases": [
      "rate limit",
      "rate limits",
      "rate limiter",
      "rate limiters"
    ],
    "html": "<p>Capping how many requests a client may make in a period of time, to protect a service and share its capacity fairly.</p>\n        <p><a href=\"docs/token-bucket-rate-limiting.html\">Token bucket rate limiting</a> explains the most common algorithm.</p>",
    "href": "docs/glossary.html#rate-limiting"
  },
  {
    "id": "read-replica",
    "term": "Read replica",
    "aliases": [
      "read replicas"
    ],
    "html": "<p>A copy of a database that serves reads and follows the primary asynchronously, so it can lag slightly behind.</p>",
    "href": "docs/glossary.html#read-replica"
  },
  {
    "id": "retry-after",
    "term": "Retry-After",
    "aliases": [],
    "html": "<p>An HTTP response header that tells the client how long to wait before retrying, sent with <code>429</code> or <code>503</code>.</p>\n        <p><a href=\"https://www.rfc-editor.org/rfc/rfc9110#field.retry-after\">RFC 9110 §10.2.3</a></p>",
    "href": "docs/glossary.html#retry-after"
  },
  {
    "id": "retry-budget",
    "term": "Retry budget",
    "aliases": [
      "retry budgets"
    ],
    "html": "<p>A cap on retries as a fraction of normal traffic (for example 10%). It stops retries from multiplying load during an outage.</p>",
    "href": "docs/glossary.html#retry-budget"
  },
  {
    "id": "slo",
    "term": "SLO",
    "aliases": [
      "SLOs",
      "service level objective",
      "service level objectives"
    ],
    "html": "<p>A service level objective: a reliability target, such as 99.9% of requests succeeding over 30 days. It is set below 100% on purpose, leaving an error budget.</p>",
    "href": "docs/glossary.html#slo"
  },
  {
    "id": "tls",
    "term": "TLS",
    "aliases": [
      "transport layer security"
    ],
    "html": "<p>Transport Layer Security: the protocol that encrypts and authenticates a connection, as in HTTPS. A gateway that \"terminates TLS\" decrypts traffic there.</p>",
    "href": "docs/glossary.html#tls"
  },
  {
    "id": "token-bucket",
    "term": "Token bucket",
    "aliases": [
      "token buckets"
    ],
    "html": "<p>A rate limiter that refills tokens at rate <em>r</em> up to a capacity <em>b</em>, and admits each request only by spending a token. It allows bursts up to <em>b</em> but enforces <em>r</em> on average.</p>\n        <p><a href=\"docs/token-bucket-rate-limiting.html\">Token bucket rate limiting</a></p>",
    "href": "docs/glossary.html#token-bucket"
  }
];
