/* GENERATED by `npm run index` from docs/. Do not edit. */
window.BH_SITE = {
 "pages": [
  {
   "href": "docs/adr-001-rate-limit-in-each-service.html",
   "title": "ADR-001: Rate limit inside each service",
   "kind": "decision",
   "status": "superseded",
   "date": "2025-11-12",
   "description": "Each service enforces its own per-client token bucket in process, so we can ship limits before launch without new infrastructure.",
   "supersedes": "",
   "supersededBy": "docs/adr-002-rate-limit-at-the-edge.html"
  },
  {
   "href": "docs/adr-002-rate-limit-at-the-edge.html",
   "title": "ADR-002: Rate limit at the edge gateway",
   "kind": "decision",
   "status": "accepted",
   "date": "2026-10-05",
   "description": "Enforce one per-client token bucket in the gateway, with state in Redis, so limits hold however many services and replicas run behind it.",
   "supersedes": "docs/adr-001-rate-limit-in-each-service.html",
   "supersededBy": ""
  },
  {
   "href": "docs/component-gallery.html",
   "title": "Component gallery",
   "kind": "reference",
   "status": "accepted",
   "date": "2026-10-05",
   "description": "Every building block in the theme, with the markup to use it. The visual reference for authors and agents.",
   "supersedes": "",
   "supersededBy": ""
  },
  {
   "href": "docs/edge-rate-limiting-design.html",
   "title": "Moving rate limiting to the edge",
   "kind": "design",
   "status": "review",
   "date": "2026-10-05",
   "description": "Replace per-service limiters with one token bucket per client in the gateway, backed by Redis, so a client's limit holds however far we scale.",
   "supersedes": "",
   "supersededBy": ""
  },
  {
   "href": "docs/glossary.html",
   "title": "Glossary",
   "kind": "reference",
   "status": "accepted",
   "date": "2026-10-05",
   "description": "Shared definitions for the terms used across these documents. Words defined here are underlined on every page; hover or tap one to see its definition.",
   "supersedes": "",
   "supersededBy": ""
  },
  {
   "href": "docs/token-bucket-rate-limiting.html",
   "title": "Token bucket rate limiting",
   "kind": "explainer",
   "status": "accepted",
   "date": "2026-10-05",
   "description": "How a token bucket admits bursts but enforces an average rate — with a live simulation, implementations, and the mistakes that bite in production.",
   "supersedes": "",
   "supersededBy": ""
  }
 ],
 "backlinks": {
  "docs/token-bucket-rate-limiting.html": [
   {
    "href": "docs/adr-002-rate-limit-at-the-edge.html#context",
    "title": "ADR-002: Rate limit at the edge gateway",
    "section": "Context"
   },
   {
    "href": "docs/glossary.html",
    "title": "Glossary",
    "section": ""
   }
  ],
  "docs/edge-rate-limiting-design.html": [
   {
    "href": "docs/adr-002-rate-limit-at-the-edge.html#context",
    "title": "ADR-002: Rate limit at the edge gateway",
    "section": "Context"
   }
  ],
  "docs/glossary.html": [
   {
    "href": "docs/component-gallery.html#glossary-terms",
    "title": "Component gallery",
    "section": "Glossary terms"
   }
  ],
  "docs/adr-001-rate-limit-in-each-service.html": [
   {
    "href": "docs/edge-rate-limiting-design.html#context",
    "title": "Moving rate limiting to the edge",
    "section": "Context & problem"
   }
  ],
  "docs/adr-002-rate-limit-at-the-edge.html": [
   {
    "href": "docs/edge-rate-limiting-design.html#decision",
    "title": "Moving rate limiting to the edge",
    "section": "Decision"
   }
  ]
 }
};
