/* GENERATED by `npm run index` from docs/. Do not edit. */
window.BH_SITE = {
 "pages": [
  {
   "href": "docs/component-gallery.html",
   "title": "Component gallery",
   "kind": "reference",
   "status": "accepted",
   "date": "2026-10-05",
   "description": "Every building block in the theme, with the markup to use it. The visual reference for authors and agents."
  },
  {
   "href": "docs/glossary.html",
   "title": "Glossary",
   "kind": "reference",
   "status": "accepted",
   "date": "2026-10-05",
   "description": "Shared definitions for the terms used across these documents. Words defined here are underlined on every page; hover or tap one to see its definition."
  },
  {
   "href": "docs/token-bucket-rate-limiting.html",
   "title": "Token bucket rate limiting",
   "kind": "explainer",
   "status": "accepted",
   "date": "2026-10-05",
   "description": "How a token bucket admits bursts but enforces an average rate — with a live simulation, implementations, and the mistakes that bite in production."
  }
 ],
 "backlinks": {
  "docs/glossary.html": [
   {
    "href": "docs/component-gallery.html#glossary-terms",
    "title": "Component gallery",
    "section": "Glossary terms"
   }
  ],
  "docs/token-bucket-rate-limiting.html": [
   {
    "href": "docs/glossary.html",
    "title": "Glossary",
    "section": ""
   }
  ]
 }
};
